/** Bekannte Künstler → Genre (case-insensitive Keys) */
const ARTIST_GENRES = {
  anyma: 'Melodic Techno',
  mrak: 'Melodic Techno',
  'charlotte de witte': 'Techno',
  'charlotte de witte b2b amelie lens': 'Techno',
  'amelie lens': 'Techno',
  hardwell: 'Big Room',
  'sub zero project': 'Hardstyle',
  'hardwell b2b sub zero project': 'Big Room',
  'martin garrix': 'Big Room',
  alok: 'Brazilian Bass',
  alesso: 'Progressive House',
  fisher: 'Tech House',
  'fisher (oz)': 'Tech House',
  'mind against': 'Melodic Techno',
  'miss monique': 'Melodic Techno',
  artbat: 'Melodic Techno',
  'sara landry': 'Techno',
  'nicole moudaber': 'Techno',
  'adam beyer': 'Techno',
  'charlotte de witte': 'Techno',
  'kölsch': 'Melodic Techno',
  kolsch: 'Melodic Techno',
  'indira paganotto': 'Techno',
  'da tweekaz': 'Hardstyle',
  'sub zero project': 'Hardstyle',
  'headhunterz': 'Hardstyle',
  'wildstylez': 'Hardstyle',
  neelix: 'Psytrance',
  omiki: 'Psytrance',
  'vini vici': 'Psytrance',
  'armin van buuren': 'Trance',
  'above & beyond': 'Trance',
  'tiësto': 'Big Room',
  tiesto: 'Big Room',
  'timmy trumpet': 'Big Room',
  'steve aoki': 'Big Room',
  'david guetta': 'EDM',
  'calvin harris': 'EDM',
  'swedish house mafia': 'Progressive House',
  'eric prydz': 'Progressive House',
  'carl cox': 'Techno',
  'charlotte de witte': 'Techno',
  'amelie lens': 'Techno',
  'charlotte de witte b2b amelie lens': 'Techno',
  'fred again': 'UK Garage',
  'fred again..': 'UK Garage',
  'disclosure': 'House',
  'camelphat': 'Melodic House',
  'mau p': 'Tech House',
  'john summit': 'Tech House',
  'dom dolla': 'Tech House',
  'peggy gou': 'House',
  'four tet': 'Electronic',
  'jamie xx': 'Electronic',
  'bicep': 'Electronic',
  'kettama': 'Tech House',
  'michael bibi': 'Tech House',
  'kettama b2b michael bibi': 'Tech House',
  'modeselektor': 'Electronic',
  'sally c': 'House',
  'young marco': 'House',
  'sasha': 'House',
  'thakzin': 'Afro House',
  vanco: 'Afro House',
  'da capo': 'Afro House',
  caiiro: 'Afro House',
  'enoo napa': 'Afro House',
  'camo & krooked': 'Drum & Bass',
  kanine: 'Drum & Bass',
  'a little sound': 'Drum & Bass',
  borgore: 'Dubstep',
  'æon:mode': 'Dubstep',
  'alison wonderland': 'Bass',
  'junkie kid': 'Hardcore',
  'gpf': 'Hardcore',
  'dr donk': 'Hardcore',
  'sandy warez': 'Hardcore',
  rozay: 'Hardcore',
  rozie: 'Hardcore',
  diffrent: 'Hardcore',
  'nicky romero': 'Progressive House',
  'r3hab': 'Big Room',
  'ofenbach': 'EDM',
  'sam feldt': 'Deep House',
  'mike williams': 'Future House',
  'chainsmokers': 'EDM',
  nervo: 'EDM',
  'armin van buuren': 'Trance',
  'vini vici': 'Psytrance',
  'john oo fleming': 'Trance',
  'hi profile': 'Psytrance',
  'fabio fusco': 'Psytrance',
  'anyma': 'Melodic Techno',
  'tale of us': 'Melodic Techno',
  'afterlife': 'Melodic Techno',
  'massano': 'Melodic Techno',
  'keinemusik': 'Afro House',
  'black coffee': 'Afro House',
  '&me': 'Melodic House',
  'rampa': 'Melodic House',
  'adam port': 'Afro House',
  'who made who': 'Melodic House',
  'solomun': 'Melodic Techno',
  'dixon': 'Melodic House',
  'amelie lens': 'Techno',
  'charlotte de witte': 'Techno',
  'i hate models': 'Techno',
  '999999999': 'Techno',
  'reinier zonneveld': 'Techno',
  'kobosil': 'Techno',
  'dax j': 'Techno',
  'pan-pot': 'Techno',
  'charlotte de witte': 'Techno',
  'eli brown': 'Tech House',
  'james hype': 'Tech House',
  'joel corry': 'House',
  'becky hill': 'Pop Dance',
  'purple disco machine': 'Disco House',
  'claptone': 'House',
  'bob sinclar': 'House',
  'dimitri vegas & like mike': 'Big Room',
  'w&w': 'Big Room',
  'blasterjaxx': 'Big Room',
  'steve angello': 'Progressive House',
  'axwell': 'Progressive House',
  'sebastian ingrosso': 'Progressive House',
  'afrojack': 'Big Room',
  'don diablo': 'Future House',
  'oliver heldens': 'Future House',
  'kygo': 'Tropical House',
  'lost frequencies': 'Deep House',
  'kungs': 'Deep House',
  'bakermat': 'Deep House',
  'oliver tree': 'Electronic',
  'grimes': 'Electronic',
  'deadmau5': 'Progressive House',
  'eric prydz': 'Progressive House',
  'lane 8': 'Melodic House',
  'yotto': 'Melodic House',
  'ben böhmer': 'Melodic House',
  'ben bohmer': 'Melodic House',
  'tinlicker': 'Melodic House',
  'monolink': 'Melodic Techno',
  'boris brejcha': 'Minimal Techno',
  'claptone': 'House',
  'fatboy slim': 'Big Beat',
  'the chemical brothers': 'Big Beat',
  'prodigy': 'Big Beat',
  'pendulum': 'Drum & Bass',
  'sub focus': 'Drum & Bass',
  'andy c': 'Drum & Bass',
  'chase & status': 'Drum & Bass',
  'wilkinson': 'Drum & Bass',
  'netsky': 'Drum & Bass',
  'high contrast': 'Drum & Bass',
  'netsky': 'Drum & Bass',
  'excision': 'Dubstep',
  'zeds dead': 'Dubstep',
  'skrillex': 'Dubstep',
  'virtual riot': 'Dubstep',
  'flux pavilion': 'Dubstep',
  'knife party': 'Dubstep',
  'nero': 'Dubstep',
  'modestep': 'Dubstep',
  'sub focus': 'Drum & Bass',
  'sigma': 'Drum & Bass',
  'wilkinson': 'Drum & Bass',
  'dimension': 'Drum & Bass',
  'friction': 'Drum & Bass',
  'hedex': 'Drum & Bass',
  'bou': 'Drum & Bass',
  'hedex': 'Drum & Bass',
  'wooli': 'Dubstep',
  'slander': 'Dubstep',
  'illenium': 'Melodic Bass',
  'seven lions': 'Melodic Bass',
  'said the sky': 'Melodic Bass',
  'porter robinson': 'Electronic',
  'madeon': 'Electronic',
  'odesza': 'Electronic',
  'flume': 'Electronic',
  'disclosure': 'House',
  'kaytranada': 'Hip-Hop House',
  'jamie xx': 'Electronic',
  'four tet': 'Electronic',
  'caribou': 'Electronic',
  'floating points': 'Electronic',
  'pangaea': 'UK Bass',
  'ben ufo': 'Techno',
  'pangaea': 'UK Bass',
  'honey dijon': 'House',
  'the blessed madonna': 'House',
  'green velvet': 'House',
  'claude vonstroke': 'Tech House',
  'fisher': 'Tech House',
  'chris lake': 'Tech House',
  'fisher': 'Tech House',
  'john summit': 'Tech House',
  'sidepiece': 'Tech House',
  'westend': 'Tech House',
  'matroda': 'Tech House',
  'noizu': 'Tech House',
  'malaa': 'Tech House',
  'acraze': 'Tech House',
  'james hurrell': 'Tech House',
  'mochakk': 'Tech House',
  'bruno furlan': 'Tech House',
  'dombresky': 'Tech House',
  'walker & royce': 'Tech House',
  'claptone': 'House',
  'claptone': 'House',
  'purple disco machine': 'Disco House',
  'lp giobbi': 'House',
  'yaeji': 'House',
  'peggy gou': 'House',
  'the blessed madonna': 'House',
  'honey dijon': 'House',
  'dj snake': 'Trap',
  'major lazer': 'Dancehall',
  'diplo': 'EDM',
  'skrillex': 'Dubstep',
  'marshmello': 'Future Bass',
  'alan walker': 'EDM',
  'alesso': 'Progressive House',
  'steve aoki': 'Big Room',
  'deorro': 'Big Room',
  'showtek': 'Big Room',
  'firebeatz': 'Big Room',
  'dimitri vegas': 'Big Room',
  'like mike': 'Big Room',
  'quintino': 'Big Room',
  'blasterjaxx': 'Big Room',
  'w&W': 'Big Room',
  'ww': 'Big Room',
  'headhunterz': 'Hardstyle',
  'wildstylez': 'Hardstyle',
  'noisecontrollers': 'Hardstyle',
  'coone': 'Hardstyle',
  'da tweekaz': 'Hardstyle',
  'atmozfears': 'Hardstyle',
  'code black': 'Hardstyle',
  'frontliner': 'Hardstyle',
  'technoboy': 'Hardstyle',
  'tuneboy': 'Hardstyle',
  'angerfist': 'Hardcore',
  'miss k8': 'Hardcore',
  'angerfist': 'Hardcore',
  'partyraiser': 'Hardcore',
  'evil activities': 'Hardcore',
  'neophyte': 'Hardcore',
  'tha watcher': 'Hardcore',
  'endymion': 'Hardcore',
  'angerfist': 'Hardcore',
  'aaron hibell': 'Melodic Techno',
  'amber broos': 'Techno',
  'juliet fox': 'Techno',
  'ely oaks': 'Big Room',
  'rose ringed': 'Melodic Techno',
  'semsei': 'Melodic Techno',
  'max styler': 'Tech House',
  'holy priest': 'Melodic Techno',
  'alleycvt': 'Bass',
  basstripper: 'UK Bass',
  ghengar: 'Dubstep',
  'sim0ne': 'Techno',
  southstar: 'Techno',
  'nico moreno': 'Techno',
  bisoux: 'Techno',
  kuko: 'Techno',
  peterblue: 'Techno',
  row1: 'Techno',
  'modeselektor (dj-set)': 'Electronic',
  'kenny montana': 'House',
  'john noseda': 'House',
  'bibi seck': 'Afro House',
  eileen: 'House',
  'young marco': 'House',
  sasha: 'House',
  'sally c': 'House',
  magik: 'Hardstyle',
  manuals: 'Hardstyle',
  'whisnu santika': 'Hardstyle',
  stadiumx: 'Progressive House',
  gravagerz: 'Hardstyle',
  'fran ares': 'Hardstyle',
  'conrad taylor': 'Hardstyle',
  'lucca van damme': 'Hardstyle',
  'funktastix': 'Hardstyle',
  bosart: 'Hardstyle',
  rino: 'Hardstyle',
  eridu: 'Melodic Techno',
  poleen: 'Melodic Techno',
  marsolo: 'Melodic Techno',
  'camilla jun': 'Melodic Techno',
  'dj sally': 'Hardstyle',
  'mike williams': 'Future House',
  'ofenbach': 'EDM',
  r3hab: 'Big Room',
  'sam feldt': 'Deep House',
  'tomas grey': 'Progressive House',
  'da tweekaz': 'Hardstyle',
  artbat: 'Melodic Techno',
  hardwell: 'Big Room',
  'nicky romero': 'Progressive House',
  'mike williams': 'Future House',
  'stadiumx': 'Progressive House',
  'gravagerz': 'Hardstyle',
};

/** Stage → typisches Genre (Fallback) */
const STAGE_GENRES = {
  mainstage: 'Big Room',
  'freedom by bud': 'EDM',
  'the rose garden': 'Drum & Bass',
  elixir: 'House',
  cage: 'Hardcore',
  'the rave cave': 'Hardcore',
  planaxis: 'Psytrance',
  'melodia by corona': 'Afro House',
  'celestia by kucoin': 'Hardcore',
  atmosphere: 'Techno',
  core: 'House',
  'crystal garden': 'Melodic Techno',
  'the great library': 'Hardstyle',
  'moose bar': 'Hardstyle',
  'house of fortune by jbl': 'Hardstyle',
};

/** Keywords im Künstlernamen → Genre */
const NAME_KEYWORDS = [
  { pattern: /psy|neelix|omiki|vini vici|astrix/i, genre: 'Psytrance' },
  { pattern: /hardstyle|tweekaz|headhunter|wildstyle|sub zero|szp|da tweekaz/i, genre: 'Hardstyle' },
  { pattern: /hardcore|gpf|donk|warez|angerfist|revenja|footworxx/i, genre: 'Hardcore' },
  { pattern: /techno|b2b.*lens|charlotte|sara landry|paganotto|kobosil|999999999/i, genre: 'Techno' },
  { pattern: /anyma|mrak|artbat|mind against|afterlife|tale of us|melodic/i, genre: 'Melodic Techno' },
  { pattern: /dnb|drum|camo|krooked|kanine|murdock|primate|hedex|bou\b/i, genre: 'Drum & Bass' },
  { pattern: /dubstep|borgore|excision|zomboy|virtual riot/i, genre: 'Dubstep' },
  { pattern: /trance|armin|vini vici|ferry|paul van dyk/i, genre: 'Trance' },
  { pattern: /house|fisher|summit|dom dolla|mau p|tech house/i, genre: 'Tech House' },
  { pattern: /garrix|alok|tiesto|hardwell|big room|w&w|blasterjaxx/i, genre: 'Big Room' },
  { pattern: /afro|thakzin|vanco|caiiro|da capo|keinemusik/i, genre: 'Afro House' },
  { pattern: /b2b/i, genre: null },
];

function normalizeKey(name) {
  return name.toLowerCase().trim().replace(/\s+/g, ' ');
}

function assignGenre(artistName, stageName) {
  const key = normalizeKey(artistName);

  if (ARTIST_GENRES[key]) return ARTIST_GENRES[key];

  for (const [artist, genre] of Object.entries(ARTIST_GENRES)) {
    if (key.includes(artist) || artist.includes(key)) return genre;
  }

  for (const { pattern, genre } of NAME_KEYWORDS) {
    if (pattern.test(artistName) && genre) return genre;
  }

  const stageKey = normalizeKey(stageName || '');
  for (const [stage, genre] of Object.entries(STAGE_GENRES)) {
    if (stageKey.includes(stage) || stage.includes(stageKey)) return genre;
  }

  if (/hosted|mc |dj set/i.test(artistName)) return 'Electronic';

  return 'Electronic';
}

module.exports = { assignGenre, ARTIST_GENRES, STAGE_GENRES };
