/**
 * Genre-Zuordnung für Tomorrowland W2 2026 (elektronische Szene 2025/2026).
 * Erlaubte Kategorien als Arrays (mehrfach möglich).
 */

const GENRES = {
  MELODIC_TECHNO: 'Melodic Techno',
  TECHNO: 'Techno',
  PEAK_TECHNO: 'Peak Time Techno',
  HARDSTYLE: 'Hardstyle',
  TECH_HOUSE: 'Tech House',
  DEEP_HOUSE: 'Deep House',
  EDM_BIGROOM: 'EDM/Big Room',
  DNB: 'Drum & Bass',
  PSYTRANCE: 'Psytrance',
};

const G = GENRES;

/** @type {Record<string, string[]>} */
const ARTIST_GENRES = {
  // ── Melodic Techno / Techno ──
  artbat: [G.MELODIC_TECHNO, G.TECHNO],
  'mind against': [G.MELODIC_TECHNO, G.TECHNO],
  'miss monique': [G.MELODIC_TECHNO],
  'kölsch': [G.MELODIC_TECHNO, G.TECHNO],
  kolsch: [G.MELODIC_TECHNO, G.TECHNO],
  massano: [G.MELODIC_TECHNO, G.TECHNO],
  fideles: [G.MELODIC_TECHNO, G.TECHNO],
  anyma: [G.MELODIC_TECHNO, G.TECHNO],
  mrak: [G.MELODIC_TECHNO, G.TECHNO],
  'tale of us': [G.MELODIC_TECHNO, G.TECHNO],
  'agents of time': [G.MELODIC_TECHNO, G.EDM_BIGROOM],
  'aaron hibell': [G.MELODIC_TECHNO, G.TECHNO],
  argy: [G.MELODIC_TECHNO, G.TECHNO],
  'adrián mills': [G.MELODIC_TECHNO],
  'adrian mills': [G.MELODIC_TECHNO],
  'holy priest': [G.MELODIC_TECHNO],
  'esin boz': [G.MELODIC_TECHNO],
  mosimann: [G.MELODIC_TECHNO],
  'mosimann b2b elfigo': [G.MELODIC_TECHNO],
  elfigo: [G.MELODIC_TECHNO],
  korolova: [G.MELODIC_TECHNO],
  quelza: [G.MELODIC_TECHNO, G.TECHNO],
  'yulia niko': [G.MELODIC_TECHNO, G.TECHNO],
  'brina knauss': [G.MELODIC_TECHNO],
  'colyn b2b sainte vie': [G.MELODIC_TECHNO, G.DEEP_HOUSE],
  colyn: [G.MELODIC_TECHNO],
  'sainte vie': [G.MELODIC_TECHNO, G.DEEP_HOUSE],
  'kevin de vries b2b meduza': [G.MELODIC_TECHNO, G.TECHNO],
  'kevin de vries': [G.MELODIC_TECHNO, G.TECHNO],
  meduza: [G.MELODIC_TECHNO, G.TECH_HOUSE],
  'amber broos b2b juliet fox': [G.TECHNO, G.PEAK_TECHNO],
  'amber broos': [G.TECHNO, G.PEAK_TECHNO],
  'juliet fox': [G.TECHNO, G.PEAK_TECHNO],
  'dino lenny b2b radioslave': [G.MELODIC_TECHNO, G.TECHNO],
  radioslave: [G.TECHNO, G.PEAK_TECHNO],
  'benwal b2b labat': [G.MELODIC_TECHNO, G.DEEP_HOUSE],
  'bisoux b2b jef nice': [G.TECHNO, G.PEAK_TECHNO],
  bisoux: [G.TECHNO, G.PEAK_TECHNO],
  'blasha & allatt': [G.MELODIC_TECHNO, G.TECHNO],
  capoon: [G.MELODIC_TECHNO],
  'cham b2b uneak': [G.MELODIC_TECHNO],
  decagon: [G.MELODIC_TECHNO],
  deco: [G.MELODIC_TECHNO],
  eimco: [G.MELODIC_TECHNO],
  eme: [G.MELODIC_TECHNO],
  'emilija b2b fenrick': [G.MELODIC_TECHNO],
  guz: [G.MELODIC_TECHNO, G.TECHNO],
  'haai b2b the blessed madonna': [G.TECHNO, G.DEEP_HOUSE],
  halo: [G.MELODIC_TECHNO],
  'halō': [G.MELODIC_TECHNO],
  iosio: [G.MELODIC_TECHNO],
  'iris rooth': [G.MELODIC_TECHNO],
  joa: [G.MELODIC_TECHNO],
  kamma: [G.DEEP_HOUSE, G.MELODIC_TECHNO],
  karakals: [G.MELODIC_TECHNO],
  kellar: [G.MELODIC_TECHNO],
  kneiz: [G.MELODIC_TECHNO],
  locus: [G.MELODIC_TECHNO, G.TECHNO],
  'lost identity': [G.MELODIC_TECHNO],
  macon: [G.MELODIC_TECHNO],
  'mahmut orhan': [G.MELODIC_TECHNO, G.DEEP_HOUSE],
  malive: [G.MELODIC_TECHNO],
  mendosa: [G.MELODIC_TECHNO],
  merow: [G.MELODIC_TECHNO],
  miro: [G.MELODIC_TECHNO],
  mirage: [G.MELODIC_TECHNO],
  mondello: [G.MELODIC_TECHNO],
  mooris: [G.MELODIC_TECHNO],
  'morgan seatree': [G.MELODIC_TECHNO],
  'mr e.': [G.MELODIC_TECHNO],
  'na:tus': [G.MELODIC_TECHNO],
  'nome.': [G.MELODIC_TECHNO],
  nome: [G.MELODIC_TECHNO],
  'ogazón': [G.MELODIC_TECHNO],
  ogazon: [G.MELODIC_TECHNO],
  'okayval': [G.MELODIC_TECHNO],
  olivex: [G.MELODIC_TECHNO],
  'oriol calvo': [G.MELODIC_TECHNO],
  portex: [G.MELODIC_TECHNO],
  prosit: [G.MELODIC_TECHNO],
  'push only': [G.MELODIC_TECHNO],
  reygel: [G.MELODIC_TECHNO],
  roma: [G.MELODIC_TECHNO],
  rosh: [G.MELODIC_TECHNO],
  'ruby xx': [G.MELODIC_TECHNO],
  'saar kuus': [G.MELODIC_TECHNO],
  'soulastico b2b tohma': [G.MELODIC_TECHNO],
  'the bobmeister': [G.MELODIC_TECHNO],
  'valentino ignoto': [G.MELODIC_TECHNO],
  'valentín huedo': [G.MELODIC_TECHNO],
  'yaz.': [G.MELODIC_TECHNO],
  'yet more': [G.MELODIC_TECHNO],
  'youri parker': [G.MELODIC_TECHNO],
  yamo: [G.MELODIC_TECHNO],
  yoshiiko: [G.MELODIC_TECHNO],
  yoshiko: [G.MELODIC_TECHNO],
  zhu: [G.DEEP_HOUSE, G.MELODIC_TECHNO],
  'oscar and the wolf': [G.MELODIC_TECHNO, G.EDM_BIGROOM],
  'kitty amor b2b curol': [G.MELODIC_TECHNO, G.DEEP_HOUSE],
  'amalie': [G.MELODIC_TECHNO],
  'anaya': [G.MELODIC_TECHNO],
  'alicia hahn': [G.MELODIC_TECHNO],
  'alex kennon': [G.MELODIC_TECHNO, G.DEEP_HOUSE],
  'alyxia bezgo b2b biianco': [G.MELODIC_TECHNO],
  'axel haube': [G.MELODIC_TECHNO],
  calao: [G.MELODIC_TECHNO],
  callush: [G.MELODIC_TECHNO],
  catalina: [G.MELODIC_TECHNO],
  'carly wilford': [G.MELODIC_TECHNO],
  'cristiano da silva': [G.MELODIC_TECHNO],
  delafino: [G.MELODIC_TECHNO],
  'domi re': [G.MELODIC_TECHNO],
  dominico: [G.MELODIC_TECHNO],
  dyzen: [G.MELODIC_TECHNO],
  'eli rojas': [G.MELODIC_TECHNO],
  'emilia de la paz': [G.MELODIC_TECHNO],
  flowchief: [G.MELODIC_TECHNO],
  gissa: [G.MELODIC_TECHNO],
  goddard: [G.MELODIC_TECHNO, G.TECH_HOUSE],
  'gregor salto': [G.MELODIC_TECHNO, G.DEEP_HOUSE],
  'helena lauwaert': [G.MELODIC_TECHNO],
  hyalyte: [G.MELODIC_TECHNO],
  imhappy: [G.MELODIC_TECHNO],
  irwan: [G.MELODIC_TECHNO],
  'jamie dill': [G.MELODIC_TECHNO],
  'jan v': [G.MELODIC_TECHNO],
  joulie: [G.MELODIC_TECHNO],
  'kyle starkey': [G.MELODIC_TECHNO],
  leesa: [G.MELODIC_TECHNO],
  'lennert wolfs': [G.MELODIC_TECHNO],
  licia: [G.MELODIC_TECHNO],
  'laura hoogland': [G.MELODIC_TECHNO],
  'lady s': [G.MELODIC_TECHNO],
  lou8: [G.MELODIC_TECHNO],
  meaghan: [G.MELODIC_TECHNO],
  'michael amani': [G.MELODIC_TECHNO],
  'michael amani & friends': [G.MELODIC_TECHNO],
  muze: [G.MELODIC_TECHNO],
  'naomi cazier': [G.MELODIC_TECHNO],
  nems: [G.MELODIC_TECHNO],
  'netty hugo': [G.MELODIC_TECHNO],
  newtone: [G.MELODIC_TECHNO],
  nikolina: [G.MELODIC_TECHNO],
  'nina black': [G.MELODIC_TECHNO],
  noa: [G.MELODIC_TECHNO],
  'onlynumbers': [G.MELODIC_TECHNO],
  pegassi: [G.MELODIC_TECHNO],
  quincy: [G.MELODIC_TECHNO],
  'radio cargo': [G.MELODIC_TECHNO],
  'rayco santos': [G.MELODIC_TECHNO],
  reeze: [G.MELODIC_TECHNO],
  'romanian -': [G.MELODIC_TECHNO],
  'romy janssen': [G.MELODIC_TECHNO],
  'runa evens': [G.MELODIC_TECHNO],
  saidah: [G.MELODIC_TECHNO],
  'sam girling': [G.MELODIC_TECHNO],
  sandersville: [G.MELODIC_TECHNO],
  'sea': [G.MELODIC_TECHNO],
  'séa': [G.MELODIC_TECHNO],
  shee: [G.MELODIC_TECHNO],
  spies: [G.MELODIC_TECHNO],
  stanne: [G.MELODIC_TECHNO],
  'tim bliss': [G.MELODIC_TECHNO],
  'tigerlily': [G.MELODIC_TECHNO],
  veg: [G.MELODIC_TECHNO],
  vegas: [G.MELODIC_TECHNO],
  'me n ü': [G.MELODIC_TECHNO],
  'shoarma soundsystem': [G.MELODIC_TECHNO],

  // ── Peak Time / Techno ──
  'sara landry': [G.TECHNO, G.PEAK_TECHNO],
  'indira paganotto': [G.TECHNO, G.PEAK_TECHNO],
  'i hate models': [G.TECHNO, G.PEAK_TECHNO],
  kobosil: [G.TECHNO, G.PEAK_TECHNO],
  amotik: [G.TECHNO, G.PEAK_TECHNO],
  azyr: [G.TECHNO, G.PEAK_TECHNO],
  'nico moreno': [G.TECHNO, G.PEAK_TECHNO],
  trym: [G.TECHNO, G.PEAK_TECHNO],
  'dyen b2b maddix': [G.TECHNO, G.PEAK_TECHNO],
  dyen: [G.TECHNO, G.PEAK_TECHNO],
  maddix: [G.TECHNO, G.PEAK_TECHNO, G.EDM_BIGROOM],
  'hi-lo b2b layton giordani': [G.TECHNO, G.TECH_HOUSE],
  'hi-lo': [G.TECHNO, G.TECH_HOUSE],
  'layton giordani': [G.TECHNO, G.TECH_HOUSE],
  'freddy k': [G.TECHNO, G.PEAK_TECHNO],
  'mha iri': [G.TECHNO, G.PEAK_TECHNO],
  'amelie lens presents aura': [G.TECHNO, G.PEAK_TECHNO],
  'charlotte de witte': [G.TECHNO, G.PEAK_TECHNO],
  'amelie lens': [G.TECHNO, G.PEAK_TECHNO],
  'adam beyer': [G.TECHNO, G.PEAK_TECHNO],
  'reinier zonneveld': [G.TECHNO, G.PEAK_TECHNO],
  '999999999': [G.TECHNO, G.PEAK_TECHNO],
  'dax j': [G.TECHNO, G.PEAK_TECHNO],
  'pan-pot': [G.TECHNO, G.PEAK_TECHNO],
  mandy: [G.TECHNO, G.PEAK_TECHNO],
  'annabel stop it': [G.TECHNO, G.PEAK_TECHNO],
  'natte visstick': [G.TECHNO, G.PEAK_TECHNO],
  'netherworld': [G.TECHNO, G.PEAK_TECHNO],
  niotech: [G.TECHNO, G.PEAK_TECHNO],
  'mobius one': [G.TECHNO, G.PEAK_TECHNO],
  'todiefor': [G.TECHNO, G.PEAK_TECHNO],
  'toxic twins': [G.TECHNO, G.PEAK_TECHNO],
  'the criminal sounds': [G.TECHNO, G.PEAK_TECHNO],
  'geheimzinnig soundsystem': [G.TECHNO, G.PEAK_TECHNO],
  'cherry moon legends (& friends)': [G.TECHNO, G.PEAK_TECHNO],
  'd-charged b2b serzo': [G.TECHNO, G.PEAK_TECHNO],
  'drs b2b sandy warez': [G.HARDSTYLE, G.TECHNO],
  'sandy warez': [G.HARDSTYLE],
  'partyraiser b2b bulletproof': [G.HARDSTYLE],
  partyraiser: [G.HARDSTYLE],
  'fais le beau b2b sixsixsixties': [G.TECHNO, G.PEAK_TECHNO],
  'bella claxton b2b paige tomlinson': [G.TECHNO],
  'brooke bailey b2b taliyah ayana': [G.TECHNO],
  'franc fala b2b benja': [G.TECHNO],
  'ruze b2b ranger trucco': [G.TECHNO, G.TECH_HOUSE],
  'bibi seck b2b faisal': [G.DEEP_HOUSE, G.TECHNO],
  'alan alvarez & crazy sir-g': [G.TECHNO, G.PEAK_TECHNO],
  aat: [G.TECHNO, G.PEAK_TECHNO],
  avalon: [G.PSYTRANCE, G.TECHNO],

  // ── Tech House ──
  fisher: [G.TECH_HOUSE],
  'john summit': [G.TECH_HOUSE],
  'james hype': [G.TECH_HOUSE, G.EDM_BIGROOM],
  'chris lorenzo': [G.TECH_HOUSE],
  'odd mob': [G.TECH_HOUSE],
  'ayybo b2b odd mob': [G.TECH_HOUSE],
  ayybo: [G.TECH_HOUSE],
  'max styler': [G.TECH_HOUSE],
  hugel: [G.TECH_HOUSE, G.DEEP_HOUSE],
  'gorgon city': [G.TECH_HOUSE, G.DEEP_HOUSE],
  'sonny fodera': [G.TECH_HOUSE, G.DEEP_HOUSE],
  'lp giobbi': [G.TECH_HOUSE, G.DEEP_HOUSE],
  morten: [G.TECH_HOUSE, G.EDM_BIGROOM],
  'john noseda': [G.TECH_HOUSE],
  'mall grab': [G.TECH_HOUSE, G.DEEP_HOUSE],
  'belters only': [G.TECH_HOUSE],
  'franky kloeck': [G.TECH_HOUSE],
  'mr. belt & wezol': [G.TECH_HOUSE],
  'laidback luke': [G.TECH_HOUSE, G.EDM_BIGROOM],
  lammer: [G.TECH_HOUSE],
  'chocolate puma': [G.TECH_HOUSE, G.EDM_BIGROOM],
  bhaskar: [G.TECH_HOUSE, G.DEEP_HOUSE],
  'dimitri cooman': [G.TECH_HOUSE],
  'jo cox': [G.TECH_HOUSE],
  joezi: [G.TECH_HOUSE, G.DEEP_HOUSE],
  shimza: [G.TECH_HOUSE, G.DEEP_HOUSE],
  'simon b': [G.TECH_HOUSE],
  'sick individuals': [G.TECH_HOUSE, G.EDM_BIGROOM],
  'swanky tunes': [G.TECH_HOUSE, G.EDM_BIGROOM],
  malugi: [G.TECH_HOUSE],
  mairee: [G.TECH_HOUSE, G.EDM_BIGROOM],
  mesto: [G.TECH_HOUSE, G.EDM_BIGROOM],
  'mr. joy': [G.TECH_HOUSE],
  'mr. rewind': [G.TECH_HOUSE],
  odssey: [G.TECH_HOUSE],
  regi: [G.TECH_HOUSE, G.EDM_BIGROOM],
  'roddy lima': [G.TECH_HOUSE, G.DEEP_HOUSE],
  'b jones': [G.TECH_HOUSE],
  bassbrain: [G.TECH_HOUSE],
  bazzy: [G.TECH_HOUSE],
  'benny plays': [G.TECH_HOUSE],
  'boy&girl': [G.TECH_HOUSE],
  'butterfly effect': [G.TECH_HOUSE],
  'danny corten': [G.TECH_HOUSE],
  'dany neville': [G.TECH_HOUSE],
  'dino': [G.TECH_HOUSE],
  flash: [G.TECH_HOUSE],
  'jeroen delodder': [G.TECH_HOUSE],
  'jessica audiffred': [G.TECH_HOUSE],
  'jorn pricez': [G.TECH_HOUSE],
  'justin wilkes': [G.TECH_HOUSE],
  'knox kind': [G.TECH_HOUSE],
  'kurt verheyen': [G.TECH_HOUSE],
  lekkerfaces: [G.TECH_HOUSE],
  'lisa korver': [G.TECH_HOUSE],
  'larry masmero': [G.TECH_HOUSE],
  'mark with a k & mc chucky': [G.TECH_HOUSE, G.HARDSTYLE],
  mattn: [G.TECH_HOUSE, G.EDM_BIGROOM],
  'mc stretch': [G.TECH_HOUSE, G.EDM_BIGROOM],
  'merow': [G.TECH_HOUSE],
  'mero b2b daire': [G.TECH_HOUSE],
  'pat krimson': [G.TECH_HOUSE, G.EDM_BIGROOM],
  'push only': [G.TECH_HOUSE],
  'the rocketman': [G.TECH_HOUSE, G.EDM_BIGROOM],
  vinne: [G.TECH_HOUSE, G.EDM_BIGROOM],
  'vitor falabella': [G.TECH_HOUSE],
  '2hot2play': [G.TECH_HOUSE],
  '5napback': [G.TECH_HOUSE, G.EDM_BIGROOM],
  '$hirak': [G.TECH_HOUSE],
  angemi: [G.TECH_HOUSE, G.EDM_BIGROOM],
  'dj art': [G.TECH_HOUSE],
  'dj ghost': [G.TECH_HOUSE],
  'dj lex': [G.TECH_HOUSE],

  // ── Deep House ──
  'lost frequencies': [G.DEEP_HOUSE, G.EDM_BIGROOM],
  'calvin harris': [G.EDM_BIGROOM, G.DEEP_HOUSE],
  kaskade: [G.DEEP_HOUSE, G.EDM_BIGROOM],
  'purple disco machine': [G.DEEP_HOUSE, G.TECH_HOUSE],
  'camelphat': [G.DEEP_HOUSE, G.MELODIC_TECHNO],
  'elderbrook': [G.DEEP_HOUSE],
  'delafino & luna fino': [G.DEEP_HOUSE, G.MELODIC_TECHNO],
  'soulastico': [G.DEEP_HOUSE, G.MELODIC_TECHNO],
  tohma: [G.MELODIC_TECHNO],
  'omdat het kan & average rob': [G.DEEP_HOUSE, G.TECH_HOUSE],
  'planet groove dj\'s': [G.DEEP_HOUSE],
  'geheimzinnig': [G.DEEP_HOUSE],

  // ── EDM / Big Room ──
  'martin garrix': [G.EDM_BIGROOM],
  hardwell: [G.EDM_BIGROOM, G.HARDSTYLE],
  alok: [G.EDM_BIGROOM],
  alesso: [G.EDM_BIGROOM],
  'timmy trumpet': [G.EDM_BIGROOM],
  'steve aoki': [G.EDM_BIGROOM],
  'dimitri vegas & like mike': [G.EDM_BIGROOM],
  'nicky romero': [G.EDM_BIGROOM],
  'mike williams': [G.EDM_BIGROOM],
  'afrojack b2b r3hab': [G.EDM_BIGROOM],
  afrojack: [G.EDM_BIGROOM],
  r3hab: [G.EDM_BIGROOM],
  'sebastian ingrosso': [G.EDM_BIGROOM, G.MELODIC_TECHNO],
  'steve angello': [G.EDM_BIGROOM, G.MELODIC_TECHNO],
  'like mike': [G.EDM_BIGROOM],
  illenium: [G.EDM_BIGROOM],
  'paris hilton': [G.EDM_BIGROOM],
  vikkstar: [G.EDM_BIGROOM],
  kaaze: [G.EDM_BIGROOM],
  'dada life': [G.EDM_BIGROOM],
  'd.o.d': [G.EDM_BIGROOM],
  'alan walker': [G.EDM_BIGROOM],
  deorro: [G.EDM_BIGROOM],
  bassjackers: [G.EDM_BIGROOM],
  nervo: [G.EDM_BIGROOM],
  novah: [G.EDM_BIGROOM],
  'ely oaks': [G.EDM_BIGROOM],
  'henri pfr': [G.EDM_BIGROOM],
  'lucas & steve': [G.EDM_BIGROOM],
  quintino: [G.EDM_BIGROOM],
  'yves v': [G.EDM_BIGROOM],
  'yves v b2b stadiumx': [G.EDM_BIGROOM, G.HARDSTYLE],
  stadiumx: [G.HARDSTYLE, G.EDM_BIGROOM],
  'armin van buuren': [G.EDM_BIGROOM],
  'sander van doorn': [G.EDM_BIGROOM],
  'thomas gold': [G.EDM_BIGROOM],
  chuckie: [G.EDM_BIGROOM],
  'dannic b2b dyro': [G.EDM_BIGROOM],
  dannic: [G.EDM_BIGROOM],
  dyro: [G.EDM_BIGROOM],
  'd. guaetta b2b neon': [G.EDM_BIGROOM],
  cyril: [G.EDM_BIGROOM],
  'lucky luke': [G.EDM_BIGROOM],
  'lucca van damme': [G.HARDSTYLE, G.EDM_BIGROOM],
  'martin trevy': [G.EDM_BIGROOM],
  'kriss reeve': [G.EDM_BIGROOM],
  'uberjak\'d feat ella young': [G.EDM_BIGROOM],
  'bingo players with iceman': [G.EDM_BIGROOM],
  'dj furax': [G.EDM_BIGROOM, G.HARDSTYLE],
  'dj f.r.a.n.k': [G.EDM_BIGROOM],
  blazy: [G.EDM_BIGROOM],
  'bobbi antonni': [G.EDM_BIGROOM],
  bouncy: [G.EDM_BIGROOM],
  'brian': [G.EDM_BIGROOM],
  'bountyhunter': [G.EDM_BIGROOM],
  'callush': [G.EDM_BIGROOM],
  'catalina': [G.EDM_BIGROOM],
  'chuckie': [G.EDM_BIGROOM],
  'diego miranda b2b jerry davila': [G.EDM_BIGROOM],
  'henri pfr': [G.EDM_BIGROOM],
  'jaël ost & magik': [G.HARDSTYLE, G.EDM_BIGROOM],
  magik: [G.HARDSTYLE],
  'kav verhouzer & de hofnar presents: eurodance': [G.EDM_BIGROOM],
  'leesa': [G.EDM_BIGROOM],
  mesto: [G.EDM_BIGROOM],
  'maite dedecker': [G.EDM_BIGROOM],
  'superheroes': [G.EDM_BIGROOM],
  'symphony of unity': [G.EDM_BIGROOM],
  'the straikerz': [G.HARDSTYLE, G.EDM_BIGROOM],
  'warface': [G.HARDSTYLE],
  'wilkinson': [G.DNB],
  'x&trick': [G.PSYTRANCE, G.EDM_BIGROOM],

  // ── Hardstyle ──
  'sub zero project': [G.HARDSTYLE],
  'da tweekaz': [G.HARDSTYLE],
  'brennan heart': [G.HARDSTYLE],
  coone: [G.HARDSTYLE],
  'sound rush': [G.HARDSTYLE],
  warface: [G.HARDSTYLE],
  'hard driver': [G.HARDSTYLE],
  blastoyz: [G.HARDSTYLE, G.PSYTRANCE],
  terrorclown: [G.HARDSTYLE],
  villain: [G.HARDSTYLE],
  'xijaro & pitch': [G.HARDSTYLE],
  'lny tnz: jump never dies (take-over)': [G.HARDSTYLE],
  'noise mafia': [G.HARDSTYLE],
  'the purge': [G.HARDSTYLE],
  'the straikerz': [G.HARDSTYLE],
  'darren styles': [G.HARDSTYLE],
  'dj furax': [G.HARDSTYLE, G.EDM_BIGROOM],
  'drs': [G.HARDSTYLE],
  'hardwell': [G.HARDSTYLE, G.EDM_BIGROOM],
  'jaël ost & magik': [G.HARDSTYLE],
  'luca van damme': [G.HARDSTYLE],
  'lucca van damme': [G.HARDSTYLE],
  'mark with a k & mc chucky': [G.HARDSTYLE],
  'partyraiser': [G.HARDSTYLE],
  'sandy warez': [G.HARDSTYLE],
  'stadiumx': [G.HARDSTYLE],
  'yves v b2b stadiumx': [G.HARDSTYLE, G.EDM_BIGROOM],
  'andre hazes': [G.HARDSTYLE],
  'bazz': [G.HARDSTYLE],
  'beat controllers': [G.HARDSTYLE],
  'b Jones': [G.HARDSTYLE],
  'bassbrain': [G.HARDSTYLE],
  'benwal': [G.HARDSTYLE],
  labat: [G.HARDSTYLE],
  blazy: [G.HARDSTYLE],
  'borgore': [G.DNB, G.EDM_BIGROOM],
  'brian': [G.HARDSTYLE],
  capoon: [G.HARDSTYLE],
  'dj f.r.a.n.k': [G.HARDSTYLE],
  'dj furax': [G.HARDSTYLE],
  'hard driver': [G.HARDSTYLE],
  'jeroen delodder': [G.HARDSTYLE],
  'justin wilkes': [G.HARDSTYLE],
  'lny tnz': [G.HARDSTYLE],
  'noise mafia': [G.HARDSTYLE],
  'pat krimson': [G.HARDSTYLE],
  prosit: [G.HARDSTYLE],
  'the criminal sounds': [G.HARDSTYLE],
  'the rocketman': [G.HARDSTYLE],
  'the purge': [G.HARDSTYLE],
  'toxic twins': [G.HARDSTYLE],
  'yves v': [G.HARDSTYLE],

  // ── Drum & Bass ──
  'chase & status (dj set)': [G.DNB],
  'chase & status': [G.DNB],
  wilkinson: [G.DNB],
  netsky: [G.DNB],
  'bou + b live 247': [G.DNB],
  bou: [G.DNB],
  andromedik: [G.DNB],
  ghengar: [G.DNB],
  basstripper: [G.DNB],
  'bullet tooth': [G.DNB],
  'riot ten': [G.DNB],
  'sullivan king': [G.DNB, G.EDM_BIGROOM],
  borgore: [G.DNB, G.EDM_BIGROOM],
  alleycvt: [G.DNB],
  'a little sound': [G.DNB],
  camo: [G.DNB],
  kanine: [G.DNB],
  hedex: [G.DNB],
  'murdock': [G.DNB],
  primate: [G.DNB],
  'hedex': [G.DNB],
  'hedex b2b': [G.DNB],
  'shimza': [G.DNB],
  'shawiya tribe': [G.DNB],
  'hedex': [G.DNB],

  // ── Psytrance ──
  somnia: [G.PSYTRANCE],
  'electric universe': [G.PSYTRANCE],
  phaxe: [G.PSYTRANCE],
  firaga: [G.PSYTRANCE],
  blastoyz: [G.PSYTRANCE, G.HARDSTYLE],
  avalon: [G.PSYTRANCE],
  'x&trick': [G.PSYTRANCE],
  neelix: [G.PSYTRANCE],
  omiki: [G.PSYTRANCE],
  'vini vici': [G.PSYTRANCE],
  'hi profile': [G.PSYTRANCE],
  'john oo fleming': [G.PSYTRANCE],
  'fabio fusco': [G.PSYTRANCE],
  'cyborg-18': [G.PSYTRANCE],
  'mad maxx': [G.PSYTRANCE],
  'trip-tamine': [G.PSYTRANCE],
  'yannick thiry': [G.PSYTRANCE],

  // ── Sonstige bekannte Acts ──
  'armin van buuren': [G.EDM_BIGROOM],
  'steve aoki': [G.EDM_BIGROOM],
  'illenium': [G.EDM_BIGROOM],
  'fisher (oz)': [G.TECH_HOUSE],
  'peggy gou': [G.TECH_HOUSE, G.DEEP_HOUSE],
  'dom dolla': [G.TECH_HOUSE],
  'mau p': [G.TECH_HOUSE],
  'carl cox': [G.TECHNO, G.PEAK_TECHNO],
  'eric prydz': [G.MELODIC_TECHNO, G.TECHNO],
  'boris brejcha': [G.MELODIC_TECHNO, G.TECHNO],
  'monolink': [G.MELODIC_TECHNO],
  'ben böhmer': [G.MELODIC_TECHNO],
  'ben bohmer': [G.MELODIC_TECHNO],
  tinlicker: [G.MELODIC_TECHNO],
  'four tet': [G.DEEP_HOUSE, G.MELODIC_TECHNO],
  'jamie xx': [G.DEEP_HOUSE],
  bicep: [G.MELODIC_TECHNO],
  'fred again': [G.DEEP_HOUSE, G.TECH_HOUSE],
  'fred again..': [G.DEEP_HOUSE, G.TECH_HOUSE],
  disclosure: [G.DEEP_HOUSE, G.TECH_HOUSE],
  'black coffee': [G.DEEP_HOUSE, G.MELODIC_TECHNO],
  '&me': [G.MELODIC_TECHNO, G.DEEP_HOUSE],
  rampa: [G.MELODIC_TECHNO],
  'adam port': [G.DEEP_HOUSE, G.MELODIC_TECHNO],
  solomun: [G.MELODIC_TECHNO],
  dixon: [G.MELODIC_TECHNO, G.DEEP_HOUSE],
  'nicole moudaber': [G.TECHNO, G.PEAK_TECHNO],
  'carl cox': [G.TECHNO, G.PEAK_TECHNO],
  'eli brown': [G.TECH_HOUSE],
  'joel corry': [G.EDM_BIGROOM],
  'becky hill': [G.EDM_BIGROOM],
  'purple disco machine': [G.DEEP_HOUSE],
  claptone: [G.DEEP_HOUSE, G.TECH_HOUSE],
  'bob sinclar': [G.DEEP_HOUSE],
  'don diablo': [G.EDM_BIGROOM],
  'oliver heldens': [G.EDM_BIGROOM],
  kygo: [G.DEEP_HOUSE, G.EDM_BIGROOM],
  kungs: [G.DEEP_HOUSE, G.EDM_BIGROOM],
  bakermat: [G.DEEP_HOUSE],
  'deadmau5': [G.MELODIC_TECHNO, G.TECHNO],
  'lane 8': [G.MELODIC_TECHNO],
  yotto: [G.MELODIC_TECHNO],
  'swedish house mafia': [G.EDM_BIGROOM, G.MELODIC_TECHNO],
  'above & beyond': [G.EDM_BIGROOM],
  'tiësto': [G.EDM_BIGROOM],
  tiesto: [G.EDM_BIGROOM],
  'david guetta': [G.EDM_BIGROOM],
  'showtek': [G.EDM_BIGROOM],
  firebeatz: [G.EDM_BIGROOM],
  'w&w': [G.EDM_BIGROOM],
  ww: [G.EDM_BIGROOM],
  headhunterz: [G.HARDSTYLE],
  wildstylez: [G.HARDSTYLE],
  angerfist: [G.HARDSTYLE],
  'dj snake': [G.EDM_BIGROOM],
  diplo: [G.EDM_BIGROOM],
  skrillex: [G.DNB, G.EDM_BIGROOM],
  marshmello: [G.EDM_BIGROOM],
  'skeletor yogi': [G.PSYTRANCE, G.DNB],
  'skeletor': [G.PSYTRANCE],
};

const STAGE_DEFAULTS = {
  mainstage: [G.EDM_BIGROOM],
  'freedom by bud': [G.MELODIC_TECHNO, G.TECH_HOUSE],
  'the rose garden': [G.DNB],
  elixir: [G.DEEP_HOUSE, G.TECH_HOUSE],
  cage: [G.HARDSTYLE],
  'the rave cave': [G.HARDSTYLE],
  planaxis: [G.PSYTRANCE],
  'melodia by corona': [G.DEEP_HOUSE],
  'celestia by kucoin': [G.HARDSTYLE],
  atmosphere: [G.TECHNO, G.PEAK_TECHNO],
  core: [G.DEEP_HOUSE, G.TECH_HOUSE],
  'crystal garden': [G.MELODIC_TECHNO, G.TECHNO],
  'the great library': [G.HARDSTYLE, G.EDM_BIGROOM],
  'moose bar': [G.HARDSTYLE],
  'house of fortune by jbl': [G.HARDSTYLE, G.EDM_BIGROOM],
};

const KEYWORD_RULES = [
  { pattern: /psy|neelix|omiki|vini vici|astrix|phaxe|somnia|electric universe/i, genres: [G.PSYTRANCE] },
  { pattern: /hardstyle|tweekaz|headhunter|wildstyle|sub zero|szp|warface|coone|brennan|sound rush|blastoyz/i, genres: [G.HARDSTYLE] },
  { pattern: /hardcore|gpf|donk|warez|angerfist|partyraiser|terror/i, genres: [G.HARDSTYLE] },
  { pattern: /techno|kobosil|999999|landry|paganotto|models|amotik|azyr/i, genres: [G.TECHNO, G.PEAK_TECHNO] },
  { pattern: /anyma|mrak|artbat|afterlife|monolink|massano|kölsch|kolsch/i, genres: [G.MELODIC_TECHNO, G.TECHNO] },
  { pattern: /dnb|drum|camo|krooked|kanine|murdock|wilkinson|netsky|chase|status|bou\b|andromedik|basstripper/i, genres: [G.DNB] },
  { pattern: /dubstep|borgore|excision|zomboy/i, genres: [G.DNB] },
  { pattern: /trance|armin|ferry|paul van dyk/i, genres: [G.EDM_BIGROOM] },
  { pattern: /house|fisher|summit|dom dolla|mau p|fodera|gorgon|belters/i, genres: [G.TECH_HOUSE] },
  { pattern: /garrix|alok|tiesto|hardwell|afrojack|alesso|guetta|harris|trumpet|aoki|vegas|mike williams|nicky|quintino|walker/i, genres: [G.EDM_BIGROOM] },
  { pattern: /deep|lost frequencies|kaskade|camelphat|disclosure/i, genres: [G.DEEP_HOUSE] },
];

function normalizeKey(name) {
  return name
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim()
    .replace(/\s+/g, ' ');
}

function dedupe(genres) {
  return [...new Set(genres)];
}

function lookupArtist(name) {
  const key = normalizeKey(name);
  if (ARTIST_GENRES[key]) return [...ARTIST_GENRES[key]];

  for (const [artist, genres] of Object.entries(ARTIST_GENRES)) {
    if (key === artist || key.includes(artist) || artist.includes(key)) {
      return [...genres];
    }
  }
  return null;
}

function assignFromKeywords(name) {
  for (const { pattern, genres } of KEYWORD_RULES) {
    if (pattern.test(name)) return [...genres];
  }
  return null;
}

function assignFromStage(stageName) {
  const key = normalizeKey(stageName || '');
  for (const [stage, genres] of Object.entries(STAGE_DEFAULTS)) {
    if (key.includes(stage)) return [...genres];
  }
  return [G.EDM_BIGROOM];
}

function assignGenresForB2B(name, stage) {
  const parts = name.split(/\s+b2b\s+/i).map((p) => p.trim()).filter(Boolean);
  if (parts.length < 2) return null;

  const merged = new Set();
  for (const part of parts) {
    const g = assignGenres(part, stage);
    g.forEach((genre) => merged.add(genre));
  }
  return merged.size ? [...merged] : null;
}

/**
 * @param {string} artistName
 * @param {string} [stageName]
 * @returns {string[]}
 */
function assignGenres(artistName, stageName = '') {
  const direct = lookupArtist(artistName);
  if (direct) return dedupe(direct);

  const b2b = assignGenresForB2B(artistName, stageName);
  if (b2b) return dedupe(b2b);

  const keywords = assignFromKeywords(artistName);
  if (keywords) return dedupe(keywords);

  return dedupe(assignFromStage(stageName));
}

module.exports = {
  assignGenres,
  GENRES,
  ARTIST_GENRES,
};
